services:
    minidlna:
        image: antlafarge/minidlna:latest
        container_name: minidlna
        restart: on-failure:3
        volumes:
            - /storage/Shared/Audio/:/opt/Audio/:ro
            - /storage/Shared/Pictures/:/opt/Pictures/:ro
            - /storage/Shared/Videos/:/opt/Videos/:ro
        networks:
            - minidlna
        ports:
            - 1900:1900/udp
            - 8200:8200/tcp
        environment:
            TZ: Europe/Paris

networks:
    minidlna:
        driver: bridge
